# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindMyVaccine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindMyVaccine
  pod 'SwiftyJSON'

  target 'FindMyVaccineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FindMyVaccineUITests' do
    # Pods for testing
  end

end
